project:
  type: book
  output-dir: docs

book:
  title: "Uitleg GMJV rapportage in Quarto"
  author:
      - name: "Pieter Seinen"
        affiliation: "GGD Hart voor Brabant"
      - name: "Sjane van der Stappen"
        affiliation: "GGD Limburg-Noord"
    
  chapters:
    - index.qmd
    - beginnen.qmd
    - rapport-uitdraaien.qmd
    - tekst-en-layout.qmd
    - gmjv-functies-gebruiken.qmd
    - voorbeeld_grafieken.qmd
    - voorbeeld_tekstfuncties.qmd
    - voorbeeld_overige_functies.qmd
    - uploaden-swing.qmd
    - handige-bronnen.qmd
    - css.qmd
    
warning: false


