# Beginnen

## Up-to-date software

Het is belangrijk om ervoor te zorgen dat software up-to-date is. Dit is het eerste om na te kijken wanneer je tegen een foutmelding aanloopt. 

### R en RStudio
Als je met verouderde versies van Rstudio en R werkt is het mogelijk dat het script niet of anders dan bedoeld werkt. Dit geldt ook voor de libraries waar het script gebruik van maakt.
```{r, eval = F}
# Rstudio: Format ontwikkeld met versie 2024.04 (Chocolate Cosmos) 
rstudioapi::getVersion()$version
rstudioapi::getVersion()$release_name

#R: Format ontwikkeld met versie 4.30
sessionInfo()

#Libraries: zo up to date mogelijk. 
old.packages() #om te zien welke libraries verouderd zijn. 

```

### R libraries updaten
Verouderde libraries / packages kunnen ook voor problemen zorgen. Het is verstandig om updates voor libraries uit te voeren in een lege sessie waarin nog geen libraries geladen zijn. Je kan libraries als volgt updaten:

-   Klik bovenin op **Session > New Session**
-   Klik in de nieuwe sessie op **Tools > Check for Package Updates**
-   Selecteer de libraries die je wilt updaten en klik op **Install Updates**

### Voor PDF-outdraai: Google Chrome
Wanneer je het rapport als PDF wilt uitdraaien is een geupdate versie Google Chrome nodig. Als je versie van Google Chrome verouderd is zal er wel een uitvoer gemaakt worden, maar zullen de knoppen in de inhoudsgave niet goed werken.

Om achter je Chrome versie te komen klik je in google chrome rechtsboven op de drie punten. Vervolgens: **Instellingen > Over Chrome**. De versie moet ten minste **Chrome 128 zijn** (update van Augustus 2024).



## Bestanden rapportagescript downloaden van Github

-   Ga naar de 'repository' [gmjv-landelijk-format](https://github.com/ggdatascience/gmjv-landelijk-format) op de githubpagina van GGDAta

-   Klik op de groene knop **Code** en selecteer in het drop-down menu. "Download Zip".

-   Open het Zip-bestand en kies "Alles Uitpakken". Selecteer een geschikte werkmap.


## R project openen en voorbeeldrapport uitdraaien
Er is een voorbeeldrapportage die gebruik maakt van fictieve data. Deze rapportage kan je als test uitdraaien. Als dit fout gaat is er waarschijnlijk iets verouderd aan je installatie van R, Rstudio of libraries.

-   Open het bestand "gmjv-landelijk-format.Rproj" in Rstudio. Door het project te openen, in plaats van een los bestand is de werkmap automatisch ingesteld.

-   Zoek rechtsonder in Rstudio bij "files" het bestand "voorbeeld_rapportage.qmd" op.

-   Als je dit bestand hebt geopend zal Rstudio het aangeven als er nog 'libraries' zijn die je moet installeren. Er verschijnt dan een gele balk bovenaan het scherm. Klik in dat geval op "install" en wacht tot de pakketjes zijn geinstalleerd.

-   Klik nu bovenaan het scherm op "Render". R gaat nu de rapportage genereren en zal het opslaan als een html bestand **"voorbeeld_rapportage.html"** in de werkmap.