# Introductie

Op deze website wordt uitgelegd hoe je de rapportage voor GMJV 2024 kan uitdraaien en aanpassen. De rapportage is (net als deze website) gemaakt met Quarto. Met Quarto kunnen opgemaakte tekst en afbeeldingen gecombineerd worden met code. De uitleg zal ingaan op de enkele technieken die gebruikt kunnen worden om de rapportage aan te passen. Het is géén uitleg van R, Quarto of HTML en CSS. Daar zijn betere bronnen voor (zie het hoofdstuk [handige bronnen](handige-bronnen.qmd)).

Naast het Quarto boek zijn er ook filmpjes met uitleg gemaakt. Die vind je hier [Uitlegvideo's standaardrapportage GMJV](https://www.youtube.com/playlist?list=PL7kVlO1ksUH3ovDR74F9nG3G0OJCnMqIb).


## Iets melden

Het is de bedoeling dat je hier alle informatie vindt die nodig is om de rapportage uit te draaien en aan te passen.
Dat is vast niet in één keer gelukt. Als je merkt dat er informatie ontbreekt, je een idee voor verbetering hebt of als je vastloopt op een foutmelding kan je dat doorgeven. Lees hieronder goed hoe dat werkt.

::: {.callout-important title="Verzoeken en problemen melden"}

Ideeën verzoeken en foutmeldingen worden afgehandeld via GitHub en **niet via e-mail**. Op deze manier kunnen issues op tijd worden opgepakt en wordt onnodig werk voorkomen. Volg de volgende stappen:

-   Zorg bij een foutmelding eerst dat je in elk geval de voorbeeldrapportage kan uitdraaien. Als dat niet lukt controleer je eerst de stappen bij [Up-to-date software](beginnen.qmd#up-to-date-software).

-   Ga naar [gmjv-landelijk-format](https://github.com/ggdatascience/gmjv-landelijk-format) en klik op 'Issues'.

-   Lees de bestaande issues en kijk of je verzoek of foutmelding al door iemand anders is gemeld.

-   Als je verzoek of foutmelding nog niet bestaat maak je een nieuw issue aan. Je kan een  bestaand issue eventueel aanvullen door er commentaar aan toe te voegen. Voeg indien mogelijk een afbeelding, screen shot of de tekst van de error mee.

:::

## Op de hoogte blijven van updates

Volg **gmjv-landelijk-format** door in github het oogje met "watch" te  klikken. Je kan dan instellen dat je berichten te ontvangt wanneer er updates zijn. Op die manier word je van wijzigingen op de hoogte gehouden.