# PDF uitdraai en Printbaarheid

Op verzoek is het mogelijk gemaakt de rapportage als PDF op te slaan en te zorgen dat deze printbaar is. De eerste stap hiervoor is bedenken of het wel nodig is om het rapport te printen. Meestal is dat niet zo. Als het toch nodig blijkt volg je de onderstaande stappen.

## Pagina-einden bepalen d.m.v. "Header 1"

In een browser bestaan pagina's niet echt. De standaard html-uitvoer van het rapport heeft dan ook geen pagina's. Wanneer je een rapport gaat printen zijn pagina-einden wel belangrijk. Daarom is voor deze rapportage ingesteld dat pagina-einden altijd vóór een kop van niveau 1 vallen.

Let daarom goed op dat je alleen een kop van niveau 1 maakt als je een nieuwe pagina wilt beginnen.

::: callout-warning
Controleer altijd de pdf-uitvoer op het mooi overlopen van pagina's

Er zijn grenzen aan hoe veel er op één pagina past. Als je te veel grafieken of tekst onder een header van niveau 1 plaatst, zal alles wat niet past naar de volgende pagina gaan. Te veel inhoud onder één header kan dus alsnog voor een arbitraire overgang van paginas zorgen.
:::

::: {.callout-tip title="Aangepaste eigenschappen Header 1" collapse="true"}
Headers van niveau 1 krijgen voor de GMJV rapportage standaard een gekleurde achtergrond en beginnen (bij conversie naar pdf) altijd op een nieuwe pagina.

Dit zijn aangepaste eigenschappen die worden bepaald in het CSS-bestand "custom.css". Je kan deze eigenschappen in dat bestand uitzetten of wijzigen. Zie ook het hoofdstuk [CSS](css.qmd)
:::

## PDF uitdraaien

Als de pagina-einden goed ingesteld staan kan je de rapportage als PDF bestand uitdraaien. Let hierbij op dat je ten minste Google Chrome 128 hebt. Zie daarvoor ['PDF-uitdraai' in het hoofdstuk 'Beginnen'](beginnen.qmd#voor-pdf-uitdraai)

-   Open het bestand **maak_pdf_rapport.R**
-   Controleer of de variabelen **file_path**, **regiocode** en **var_gemeente** goed staan ingesteld.
-   Draai het hele script.
-   Controleer de uitvoer.
